# Generated by Django 4.1 on 2022-11-21 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_listing_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clear_date',
            field=models.DateField(default='2002-10-15'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='product.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='lease_date',
            field=models.DateField(default='2000-10-11'),
            preserve_default=False,
        ),
    ]
