# Generated by Django 4.1 on 2023-02-01 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='product.listing'),
            preserve_default=False,
        ),
    ]
